deviceGateway:
  listenPort : 19690

logs:
  logFileName: 'cp.log'

jwt:
  secret: 'aboard.about.above.across.after.against.amid.among.anti'
  apikeysecret: 'thefatbrownfoxjumpedoverthequicksilverdoveanddrovehomeinanewpickip37truck'
  ttl: -1

mongo:
  host: 'localhost'
  port: 27017
  dbName: 'cp'
  agenda: 'agenda'

socketio:
  origin: 'localhost:*'
  port: 19691
  securePort: 20143
  isSecurePortEnabled : false
  isUnSecurePortEnabled : true
  ssl:
    privateKeyFile  : './bin/ssl/privatekey.pem'
    certificateFile : './bin/ssl/certificate.pem'
    caCertsFile     : './bin/ssl/privatekey.pem'   # this is not needed when self-signed so we assign to privatekey for dev

rabbitmq:
  host: owl.rmq.cloudamqp.com #'localhost'
  login: zzqealbp #'guest'
  password: 7VuC5MbcMnU-HMxbnSuq_rbq-ywh-61a  #'guest'
  authMechanism: 'AMQPLAIN'
  vhost: zzqealbp #'/'
  reconnect: true
  reconnectBackoffStrategy: 'linear'
  reconnectExponentialLimit: 120000
  reconnectBackoffTime: 1000

cloudamqp:
  url: 'amqp://zzqealbp:7VuC5MbcMnU-HMxbnSuq_rbq-ywh-61a@owl.rmq.cloudamqp.com/zzqealbp'

# This is the development configuration
restServer:
  isSecurePortEnabled : false
  isUnSecurePortEnabled : true
  port: 19690
  securePort: 3001
  ssl:
    privateKeyFile  : './bin/ssl/privatekey.pem'
    certificateFile : './bin/ssl/certificate.pem'
    caCertsFile     : './bin/ssl/privatekey.pem'   # this is not needed when self-signed so we assign to privatekey for dev

github:
  clientID: 3be3a353b77d093a2727
  clientSecret: 689158bbeeafe661e3db3432864d42f5ce1156f3
  callbackURL: http://localhost:19690/auth/github/callback

facebook:
  appID: 1502606000005936
  appSecret: e89b0e89999ff893c0bf84a13fa71c99
  callbackURL: http://localhost:19690/auth/facebook/callback

google:
  clientID: 526563584146-t8dp70hkvbniu59kj17cspidhbedav1q.apps.googleusercontent.com
  clientSecret: df4zwW-GKjukvqnW3fy-uEMX
  callbackURL: http://localhost:19690/auth/google/callback

linkedin:
  clientID: 727a6725-7fc4-4eae-8e2b-f318c48330b8
  clientSecret: ea602421-d00f-4cf6-b6e8-1607b0f9b32c
  callbackURL: http://localhost:19690/auth/google/callback

graphfm:
  token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb252ZXJzZXBvaW50LmNvbSIsImlhdCI6MTQzMDg3ODk0OCwiZXhwIjoxNDYyNDE0OTQ5LCJhdWQiOiJncmFwaC5mbSIsInN1YiI6ImFwaSBrZXkifQ.-JL3M0se0ZwzYDFbp6EcW_1WJc6O2WXyK-ltAxGrScw'

webhook:
  url: 'http://localhost:19690/webhook/loopback'
  enterprise: 'graph.fm'

users:
  fakeEmail: '@apikey.fak'

logs:
  directory: 'logs'
